version: '3.9'

x-logging:
  &default-logging
  driver: json-file
  options:
    max-size: '100m'
    max-file: '10'
    tag: "{{.ImageName}}|{{.Name}}"

x-resources:
  &default-resources
  cpus: 0.5
  mem_limit: 256M

x-defaults:
  &defaults
  logging: *default-logging
  restart: unless-stopped
  networks:
    - loki
  <<: *default-resources

volumes:
  grafana-data:
  loki-data:
  promtail-data:
  prometheus-data:

networks:
  loki:

services:

  promtail:
    image: grafana/promtail:2.3.0
    ports:
      - 9080:9080
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - ./promtail/config.yml:/etc/promtail/config.yml:ro
      - promtail-data:/var/lib/promtail/positions
    <<: *defaults


  loki:
    image: grafana/loki:2.3.0
    ports:
      - 3100:3100
    volumes:
      - loki-data:/tmp/loki/
    <<: *defaults

  grafana:
    image: grafana/grafana:8.1.3
    ports:
      - 3000:3000
    volumes:
      - grafana-data:/var/lib/grafana
    <<: *defaults

  prometheus:
    image: prom/prometheus:v2.29.2
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    extra_hosts:
      - "host.docker.internal:host-gateway"
    <<: *defaults
