apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: devops-web-app
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: devops-web-app
    spec:
      containers:
      - name: devops-web-app
        image: maxitosh/devops_web_app:latest
        ports:
        - containerPort: 8000
