version: '3.9'
x-logging:
  &default-logging
  driver: json-file
  options:
    max-size: '100m'
    max-file: '10'
    tag: "{{.ImageName}}|{{.Name}}"

x-defaults:
  &defaults
  logging: *default-logging
  restart: unless-stopped

networks:
  app:

services:
  python_app:
    image: maxitosh/devops_web_app:${TAG:-latest}
    ports:
      - "8000:8000"
    networks:
      - app
    <<: *defaults
