---
- hosts: all
  remote_user: ubuntu

  roles:
    - role: docker_install
      become: true
      vars:
        docker_users:
          - "{{ ansible_user_id }}"

    - role: deploy_app
      vars:
        python_app_image: maxitosh/devops_web_app
        python_app_tag: latest
        python_app_port: 8000
