global:
  scrape_interval: 5s
  evaluation_interval: 5s
  scrape_timeout: 3s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets:
        - "localhost:9090"
  - job_name: "loki"
    static_configs:
      - targets:
        - "loki:3100"
  - job_name: "docker"
    static_configs:
      - targets:
        - "host.docker.internal:9323"
  - job_name: "python_app"
    static_configs:
      - targets:
        - "host.docker.internal:8000"
