apiVersion: v1
kind: Secret
metadata:
  name: credentials
  labels:
    {{- include "devops-web-app-chart.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ .Values.password | b64enc | quote }}
