# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Test
on:
  workflow_run:
    workflows: ["CI to Docker Hub"]
    types:
      - completed

jobs:
  build:

    runs-on: ubuntu-latest

    # runs within Docker container
    container:
      image: docker://${{ secrets.DOCKER_HUB_USERNAME }}/devops_web_app:latest

    steps:
    - uses: actions/checkout@v2
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        python3 -m flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        python3 -m flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        python3 -m pytest
